version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"

    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
      timezone: "America/New_York"

    labels:
      - "github-actions dependencies"

    groups:
      github-actions:
        patterns:
          - "*"
