name: "Open a new issue"
description: "Have a question or an issue? Let us know here."
title: "Enter your issue title here"
labels: []
body:
  - type: markdown
    attributes:
      value: "## Welcome!"
  - type: markdown
    attributes:
      value: >-
        We value your input and are here to help. Please use this space to describe your question, 
        issue, or suggestion with as much detail as possible. Good descriptions include 
        specific steps to reproduce the issue, documentation of the observed versus expected behavior,
        and any relevant screenshots or error messages. Your detailed account helps us to address 
        your concerns promptly and improve the `jdat-notebooks` for everyone.
  - type: input
    id: notebook-name
    attributes:
      label: "Notebook Name:"
      placeholder: "Enter the name of the notebook here..."
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Description
    validations:
      required: true
