#!/usr/bin/env bash

echo $1 > .toload_astrowidgets
voila voilable_astrowidgets.ipynb &
VOILA_PID=$!
echo "VOILA: $VOILA_PID"
sleep 2
/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe --app=http://localhost:8866
trap "kill $VOILA_PID; exit 1" INT
wait
