#!/usr/bin/env bash

echo $1 > .toload_astrowidgets
voila voilable_astrowidgets.ipynb &
VOILA_PID=$!
echo "VOILA: $VOILA_PID"
sleep 2
#open http://localhost:8866/
if [ -d "/Applications/Google\ Chrome.app" ]; then
    /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --app=http://localhost:8866
elif [ -d "/Applications/Firefox.app" ]; then
    open -a Firefox "http://localhost:8866"
fi
trap "kill $VOILA_PID; exit 1" INT
wait
